# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jdqxjioUUrQm-xgTVZKP6TpFFws6XwrH
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

# Load your dataframe here
df = pd.read_csv("Bands_new.csv")

# Handle missing genre
df['Genre detail'] = np.where(df['Genre specific'].isna(), df['Genre simple'], df['Genre specific'])

# Create the merged detail column
df['Details'] = (
    df['Genre detail'].fillna('') + '<br>' +
    '📅 ' + df['Day'].fillna('') + '<br>' +
    '⏰ ' + df['Time'].fillna('') + '<br>' +
    '🎪 ' + df['Stage'].fillna('')
)

# Grouping toggle
view_option = st.selectbox(
    "🔀 Group bands by:",
    ("Country → Genre", "Genre → Country")
)

# Decide path based on selection
if view_option == "Country → Genre":
    sunburst_path = ['Country', 'Genre simple', 'Band', 'Details']
else:
    sunburst_path = ['Genre simple', 'Country', 'Band', 'Details']

st.set_page_config(layout="wide")

st.title("Brutal Assault 2025")

# Create interactive sunburst chart
fig = px.sunburst(
    df,
    path=sunburst_path,
    title='Brutal Assault 2025',
    color=sunburst_path[0],
    color_discrete_sequence=px.colors.qualitative.Set3,
    maxdepth=2
)

fig.update_layout(
    width=900,
    height=700,
    margin=dict(t=40, l=0, r=0, b=0),
    title_font_size=24,
    legend_font_size=14
)

st.plotly_chart(fig, use_container_width=True)

fig.write_html("index.html", full_html=True, include_plotlyjs="**embed**")

