# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jdqxjioUUrQm-xgTVZKP6TpFFws6XwrH
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

# Load your dataframe here
df = pd.read_csv("Bands_new.csv")

# Handle missing genre
df['Genre detail'] = np.where(df['Genre specific'].isna(), df['Genre simple'], df['Genre specific'])

# Create the merged detail column
df['Details'] = (
    df['Genre detail'].fillna('') + '<br>' +
    '📅 ' + df['Day'].fillna('') + '<br>' +
    '⏰ ' + df['Time'].fillna('') + '<br>' +
    '🎪 ' + df['Stage'].fillna('')
)

# Grouping toggle
view_option = st.selectbox(
    "🔀 Group bands by:",
    ("Country → Genre", "Genre → Country")
)

custom_colors = {
    'Heavy metal': '#1f77b4',       # blue
    'Metalcore': '#ff7f0e',         # orange
    'Hardcore': '#2ca02c',          # green
    'Rock': '#d62728',              # red
    'Deathcore': '#9467bd',         # purple
    'Death metal': '#8c564b',       # brown
    'Grindcore': '#e377c2',         # pink
    'Black metal': '#7f7f7f',       # gray
    'Jazz': '#bcbd22',              # olive
    'Thrash metal': '#17becf',      # cyan
    'Doom metal': '#aec7e8',        # light blue
    'Post-metal': '#ffbb78',        # light orange
    'Industrial metal': '#98df8a',  # light green
    'Progressive metal': '#ff9896', # light red
    'Nu metal': '#c5b0d5',          # light purple
    'Sludge': '#c49c94',            # light brown
    'Stoner metal': '#f7b6d2',      # light pink
    'Avant-garde metal': '#c7c7c7', # light gray
    'Groove metal': '#dbdb8d',      # light olive
    'Gothic metal': '#9edae5',      # light cyan
    'Synthwave': '#393b79',         # dark blue
    'Industrial': '#637939',        # dark green
    'Viking metal': '#8c6d31',      # dark brown
    'Gothic rock': '#843c39',       # dark red
    'Rave metal': '#7b4173'         # dark purple
}

# Decide path based on selection
if view_option == "Country → Genre":
    sunburst_path = ['Country', 'Genre simple', 'Band', 'Details']
else:
    sunburst_path = ['Genre simple', 'Country', 'Band', 'Details']

st.set_page_config(layout="wide")

st.title("Brutal Assault 2025")

# Create interactive sunburst chart
fig = px.sunburst(
    df,
    path=sunburst_path,
    title='Brutal Assault 2025',
    color='Genre simple',  # color by genre
    color_discrete_map=custom_colors,
    maxdepth=2
)

fig.update_layout(
    width=900,
    height=700,
    margin=dict(t=40, l=0, r=0, b=0),
    title_font_size=24,
    legend_font_size=14
)

st.plotly_chart(fig, use_container_width=True)

fig.write_html("index.html", full_html=True, include_plotlyjs="**embed**")

